### PR TITLE
Change peach-oled to use systemd-units package configuration

### PR DESCRIPTION
**Pull request by mhfowler**
As referenced in this issue https://github.com/peachcloud/peach-img-builder/issues/2

### CODE REVIEW

**Review by mycognosist — APPROVED** [review]
@mhfowler 

This looks great. Awesome that we're able to get rid of the `post-` and `pre-` scripts completely!

One quick question: have you successfully tested removing and purging this package after installation? That's the only other thing that comes to mind. I'm sure you've already tested that.

You're welcome to go ahead and implement this change for all the other microservices 🙏🏻

**Comment by mhfowler** [comment]
I've tested that `apt-get remove` and `apt-get purge` seem to work as expected. 

I've also inspected the maintainer scripts it generates, using dpkg. 

Here for reference:

**Comment by mhfowler** [comment]
``` shell
# postrm
#!/bin/sh
set -e
# Automatically added by cargo-deb
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by cargo-deb
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask peach-oled.service >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge peach-oled.service >/dev/null || true
		deb-systemd-helper unmask peach-oled.service >/dev/null || true
	fi
fi
# End automatically added section```

**Comment by mhfowler** [comment]
``` shell
# prerm
#!/bin/sh
set -e
# Automatically added by cargo-deb
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop peach-oled.service >/dev/null || true
fi
# End automatically added section
```

**Comment by mhfowler** [comment]
``` shell
# postinst
#!/bin/sh
set -e
# Automatically added by cargo-deb
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask peach-oled.service >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled peach-oled.service; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable peach-oled.service >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state peach-oled.service >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by cargo-deb
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action peach-oled.service >/dev/null || true
	fi
fi
# End automatically added section
```

**Pull request merged**
